name: Check code style

on:
  push:
    branches:
      - prod

  pull_request:
    branches:
      - prod
jobs:
  checkcode:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Check python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          pip install pycodestyle

      - name: Run linter
        run: |
          pycodestyle .
